### ISSUE TITLE
Y U NO USE CONTAINERS? 

### ISSUE THREAD

**Issue by brucellino** [osynge/python-openstack-whenenv-integration#1]
Hi Owen, 

![oblig](http://i.imgur.com/LDIigqj.jpg)

Not to criticise at all the quality or relevance of this work, but I'm wondering if it can be compared to  [Docker's Orchestration tools](http://blog.docker.com/2015/02/orchestrating-docker-with-machine-swarm-and-compose/)

I mean, instead of building and ripping down clusters of virtual machines, one could consider doing something similar with containers. 

What's your take ?

**Comment by osynge** [comment]
I like containers, and if I was not working on storage systems I would be using them heavily.

My take:

0) I will add a link and the nice link you sent to the README.

1) This project is designed to work with jenkins or in a terminal. Jenkins is its first calling. For this reason I try to keep as much state in openstack instance markup. This means that closing down a session, can occur in a later run of a jenkins job on the same executor during buildup should tests fail and no one calls the teardown function.

1.1) running $(some_script) is not compatible with the jenkins model if I focus on cleanup.

2) I am working on ceph a storage product, so I need need to work mostly on IO and multiple disks so full virtualisation is closer to the target platform, so maybe better for the task of functional testing ceph. Docker-io may help here.

3) I have access to a private cloud running openstack and a quota on this service.

4) whatenv is intended to be reused as a plugin to whenenv, so I can transparently add shell scripts to run simple shell tests in a matrix job on multiple cluster layouts. Both whatenv and whenenv will need some work before thsi can be done, but I hope to do this at the next SUSE hack week.

5) kubernetes also looks interesting but again it is not targeting IAS.

```
https://github.com/googlecloudplatform/kubernetes
```

Thsi along with  my experiance with cluster management where parts to the design of labels.

6) the HEAT project looks very interesting too.

```
https://wiki.openstack.org/wiki/Heat
```

But I cant use this yet (as our internal cloud does not yet support it) and I need some thing working now.
